### ISSUE TITLE
Modifica html javascript

### ISSUE THREAD

**Issue by simocare** [Sdraiati/Sdraiati.github.io#32]
Modificare le strutture html che contengono i tag script, per spostarli dalla posizione attuale. Seguendo quanto detto nelle slides della prof.:
Possono apparire sia nell’header di un file HTML che nel
corpo, con funzioni molto diverse:
 header  servono per produrre contenuto su richiesta o
si occupano dell’interazione con l’utente. In generale,
definizioni di funzioni che vengono riutilizzate più volte
 Ex. codice associato agli elementi di un form
 body  script da interpretare una volta sola
 Ex. controllo su un dato specifico
quindi spostare nell'header tutti gli script di interazione (popup, ecc.)

**Comment by danesinoo** [comment]
Vorrei, ma non funziona tutto il js di interazione con l'utente nell'header, per esempio il js in modifica.js, non può stare sull'header, anzi dovrebbe stare sul footer
